---
- name: Configure ceilometer-collector server
  hosts: ceilometer-collector
  sudo: True
  gather_facts: True
  tags:
    - openstack
    - openstack-ceilometer-collector
  vars:
    component: ceilometer
    packages:
      - "{{ component }}-collector"
      - "{{ component }}-agent-central"
    services:
      - "{{ component }}-collector"
      - "{{ component }}-agent-central"
    config_files:
      - "{{ component }}.conf"

  tasks:

    - name: ensure kili-team ppa is added
      apt_repository:
        repo: ppa:kili-team/ppa
        update_cache: yes

    - name: ensure {{ component }}-collector packages are installed
      apt: 
        pkg: "{{ item }}"
        state: latest 
        update_cache: yes 
        cache_valid_time: 600
      with_items: packages

    - name: ensure services are stopped
      service: 
        name: "{{ item }}"
        state: stopped
      with_items: services

    - name: ensure {{ component }} sqlite is deleted
      file: 
        dest: /var/lib/{{ component }}/{{ component }}.sqlite 
        state: absent

    - name: update configuration files from templates
      template: 
        src: templates/etc/{{ component }}/{{ item }}
        dest: /etc/{{ component }}/{{ item }}
        owner: "{{ component }}"
        group: "{{ component }}"
        mode: 0600
      with_items: config_files

    - name: ensure services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items: services

