---
- name: rsync
  hosts: all
  sudo: True
  gather_facts: True
  tags:
    - base-env
  tasks:

    - name: ensure rsync is installed
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 600
      with_items:
        - rsync
