---
- name: register external networks on neutron
  hosts: neutron-network
  sudo: True
  gather_facts: True
  tags:
    - neutron-external-networks
  tasks:

    - name: ensure primary net is registered
      neutron_network:
        auth_url: "{{ keystone_public_url }}"
        login_tenant_name: admin
        login_username: admin
        login_password: "{{ admin_password }}"
        tenant_name: admin
        router_external: True
        name: "{{ neutron_network_conf[env_name]['primary_network']['network_name'] }}"
        state: present
      register: primary_network

    - name: ensure other networks are registered
      neutron_network:
        auth_url: "{{ keystone_public_url }}"
        login_tenant_name: admin
        login_username: admin
        login_password: "{{ admin_password }}"
        tenant_name: admin
        router_external: True
        name: "{{ item['network_name'] }}"
        state: present
      with_items: neutron_network_conf[env_name]['other_external_networks']
      register: other_network
