---
- name: Install or verify neutron database
  hosts: mysql
  sudo: True
  gather_facts: False
  tags:
    - openstack
  tasks:

    - name: ensure neutron database is present
      mysql_db: 
        name: neutron

    - name: ensure neutron database user is present
      mysql_user: 
        name: neutron 
        host: "{{ item }}" 
        password: "{{ neutron_mysql_password }}" 
        priv: neutron.*:ALL
      with_items:
        - "%"
        - localhost

    - name: ensure neutron_ml2 database is present
      mysql_db: 
        name: neutron_ml2

    - name: ensure neutron database user is present
      mysql_user: 
        name: neutron_ml2
        host: "{{ item }}" 
        password: "{{ neutron_ml2_mysql_password }}" 
        priv: neutron_ml2.*:ALL
      with_items:
        - "%"
        - localhost
