---
- name: install deployment environment
  hosts: admin-host
  sudo: True
  gather_facts: True
  tasks:

    - name: ensure basic packages are installed
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 600
      with_items:
        - python-pip
        - python-virtualenv
        - virtualenvwrapper
        - git
        - gcc
        - python-dev
        - screen
        - guestfish

    - name: create deployment user
      user: 
        name: "{{ deployment_user }}"
        shell: /bin/bash

    - name: give deployment user special permissions
      lineinfile:
        dest: /etc/sudoers
        line: "{{ deployment_user }} ALL=(ALL) NOPASSWD: /sbin/mount, /sbin/umount"
        insertafter: EOF
        backup: yes

    - name: ensure our public keys are in authorized_keys
      sudo_user: "{{ deployment_user }}"
      authorized_key: 
        key: "{{ item }}"
        user: "{{ deployment_user }}"
      with_items: ssh_authorized_keys

    - name: ensure keys directory exists
      sudo_user: "{{ deployment_user }}"
      file:
        path: "{{ item }}"
        state: directory
        mode: 0700
      with_items:
        - "/home/{{ deployment_user }}/keys"
        - "/home/{{ deployment_user }}/credentials"
        - "/home/{{ deployment_user }}/deployment"

    - name: ensure key files are present
      sudo_user: "{{ deployment_user }}"
      copy:
        mode: 0600
        src: files/admin_host/keys/
        dest: "/home/{{ deployment_user }}/keys/"

    - name: clone deployment scripts repo
      sudo_user: "{{ deployment_user }}"
      git:
        repo: git@github.com:kili/deployment_scripts
        accept_hostkey: yes
        dest: /home/deployment/scripts
        update: yes
        key_file: "/home/{{ deployment_user }}/keys/deployment_scripts/id_rsa"

    - name: ensure ansible virtualenv is present
      sudo_user: "{{ deployment_user }}"
      pip:
        virtualenv: "/home/{{ deployment_user }}/.venv"
        requirements: "/home/{{ deployment_user }}/scripts/requirements.txt"
        state: present
