---
- name: Install or verify Swift database
  hosts: mysql
  gather_facts: False
  tags:
    - openstack
  sudo: True
  tasks:

    - name: ensure swift database is present
      mysql_db: 
        name: swift

    - name: ensure swift database user is present
      mysql_user: 
        name: swift 
        host: "{{ item }}" 
        password: "{{ swift_mysql_password }}" 
        priv: swift.*:ALL
      with_items:
        - "%"
        - localhost
